### PR TITLE
Added missing #include errors

### PR DESCRIPTION
**Pull request by sinnstudio-nas**
Fixed errors related to missing includes

image

Strangely, VS 2019 would only complain sometimes about it... but now they seem resolved. I got it a few times when I tried to build master and now on 4.26 as well

image

### CODE REVIEW

**Comment by goncasmage1** [comment]
I'm  glad you found this issue!
A few notes about this:

- Only add the include necessary in the files that are actually accessing the UINavWidget
- Only add the include to the UINavWidget class in .cpp files, given that that class has a lot of stuff
- Merge this into the 4.24 branch

**Comment by goncasmage1** [comment]
Also, while you're at it, can you also remove the include to the UINavWidget class in the UINavHorizontalComponent.cpp file?

**Comment by sinnstudio-nas** [comment]
@goncasmage1 updated as per first comment.

> Also, while you're at it, can you also remove the include to the UINavWidget class in the UINavHorizontalComponent.cpp file?

I get errors if I remove the includes ther:

image

**Comment by goncasmage1** [comment]
Ok looks good to me 👍

**Pull request merged**
