### PR TITLE
Automatically sets the PlayerController in UiNav Widget as the owner

### PR DESCRIPTION
**Pull request by shukenmg**
#78 
Adds functionality to automatically get and set the player controller.
Also added 2 vars to the class defaults in the UINavWidget that control this behavior.

### CODE REVIEW

**Comment by shukenmg** [comment]
Found a breaking bug with this implementation, please do not merge yet.

**Comment by goncasmage1** [comment]
I appreciate you taking the time to try to fix this ❤️, but this pull request contains way too many changes.
I'll simply do a small change that will fix this issue and will be much more manageable. 👍

**Comment by goncasmage1** [comment]
So first of all there are a lot of indentation changes and what not that come along with this pull request, which is something that I'm not really comfortable doing.

I have a question though, is this supposed to cover the scenario where the Player Controller doesn't yet exist? If so, how can you fetch the player controller if it doesn't exist?

**Comment by shukenmg** [comment]
Closing this PR in favor of #80 
That PR fixes the indentation.

**Pull request closed without merging**
