### PR TITLE
Make sure to define pointers with nullptr

### PR DESCRIPTION
**Pull request by seb-exiin**
some pointers are not defined and may cause some garbage collection issue

### CODE REVIEW

**Review by goncasmage1 — CHANGES_REQUESTED** [review]
Thanks for this PR!
I think it looks good, but I just wanted to ask that you restore all the indentations of the properties you touched, in order to maintain consistency.
This is a coding convention I personally no longer use (and you probably don't either) but I did use it when I started working on the plugin, and I think consistency is more important.
Unless you also want to remove the indentation on *all* the properties in the plugin 😂 if you do, that's another option.

**Comment by seb-exiin** [comment]
Then can I aslo fix all the following too:
// Copyright (C) 2019 Gon�alo Marques - All Rights Reserved
to
// Copyright (C) 2019 Gonçalo Marques - All Rights Reserved

**Comment by seb-exiin** [comment]
Fixed remarks

**Review by goncasmage1 — APPROVED** [review]
Looks good!
Thanks for the effort <3

**Pull request merged**
